import test from 'node:test';import assert from 'node:assert/strict';
import {blankFinancials,initialAssumptions,buildCalculation,finiteNumber,dollars,percent,initialImpact,eventImpact,splitPeers,valuationAIIsCurrent} from './decision.mjs';
const f=()=>({...blankFinancials('EXM'),price:100,price_date:'2026-09-09',period_end:'2026-06-30',revenue:10000,operating_income:2000,cash:1000,debt:1000,shares:300});
test('blank data does not become zero valuation',()=>assert.equal(buildCalculation(blankFinancials('EXM'),initialAssumptions),null));
test('zero cash is valid, missing cash is not',()=>{assert.equal(buildCalculation({...f(),cash:0},initialAssumptions).financials.cash,0);assert.equal(buildCalculation({...f(),cash:''},initialAssumptions),null);});
test('percent inputs are fractions on server',()=>{let b=buildCalculation(f(),initialAssumptions);assert.equal(b.assumptions.discount_rate,.10);assert.equal(b.assumptions.scenarios[1].growth,.1);assert.equal(b.assumptions.sales_to_capital,3);});
test('missing scenario percent is not silently zero',()=>assert.equal(buildCalculation(f(),{...initialAssumptions,scenarios:initialAssumptions.scenarios.map(s=>({...s,growth:''}))}),null));
test('NaN infinity booleans missing strings remain unknown',()=>{for(let x of [NaN,Infinity,true,null,undefined,'',' '])assert.equal(finiteNumber(x),null);});
test('number formatting unknown vs actual zero',()=>{assert.equal(dollars(null),'—');assert.equal(dollars(0),'$0.00');assert.equal(percent(null),'—');assert.equal(percent(0),'0.0%');});
test('future earnings not positive merely scheduled',()=>assert.equal(initialImpact('EARNINGS').direction,'WAITING'));
test('conference not high priority merely attendance',()=>{assert.equal(initialImpact('CONFERENCE').importance,'LOW');assert.equal(initialImpact('CONFERENCE').direction,'NEUTRAL');});
test('unknown economic effect not low importance by default',()=>assert.equal(initialImpact('OTHER').importance,'INSUFFICIENT'));
test('no report has transparent rules label',()=>assert.match(eventImpact({category:'EARNINGS'},null,'EXM').kind,/새 AI 분석 아님/));
test('different symbol report not linked',()=>assert.equal(eventImpact({id:'local-1',category:'EARNINGS'},{symbol:'OTHER',events:[{event_id:'local-1',direction:'NEGATIVE'}]},'EXM').direction,'WAITING'));
test('new report reusing ai-index cannot inherit wrong event',()=>assert.equal(eventImpact({id:'ai-0',title:'New earnings',category:'EARNINGS'},{symbol:'EXM',events:[{event_id:'ai-0',event_title:'Old contract',direction:'NEGATIVE'}]},'EXM').direction,'WAITING'));
test('linked local candidate displays accepted interpretation',()=>assert.equal(eventImpact({id:'local-1',category:'EARNINGS'},{symbol:'EXM',events:[{event_id:'local-1',direction:'WAITING',importance:'HIGH'}]},'EXM').kind,'AI 해석 · 저장 근거 기준'));
test('peer list bounded unique and excludes target',()=>assert.deepEqual(splitPeers('exm aa AA,BB cc dd','EXM'),['AA','BB','CC']));
test('optional analyst reference absent does not make estimate',()=>assert.deepEqual(buildCalculation(f(),initialAssumptions,[{kind:'CONSENSUS',value:''}]).references,[]));
test('company vs consensus provenance unchanged',()=>{let refs=[{kind:'CONSENSUS',value:'12000',source_url:'https://example.com/c'}];assert.equal(buildCalculation(f(),initialAssumptions,refs).references[0].kind,'CONSENSUS');assert.equal(buildCalculation(f(),initialAssumptions,refs).references[0].value,12000);});
test('changing inputs does not mutate shared defaults',()=>{const before=JSON.stringify(initialAssumptions);buildCalculation(f(),initialAssumptions);assert.equal(JSON.stringify(initialAssumptions),before);});
test('AI valuation narrative tied to exact assumption hash',()=>{assert.equal(valuationAIIsCurrent({symbol:'EXM',valuation_hash:'a'},'b','EXM'),false);assert.equal(valuationAIIsCurrent({symbol:'EXM',valuation_hash:'a'},'a','EXM'),true);});
