import test from 'node:test';import assert from 'node:assert/strict';
import {defaultCalculation,matchedOutlook,eventView,filingCards,valuationDigest,researchCacheIsCurrent,humanFailure} from './desk.mjs';
const input={symbol:'TEST',company_name:'TEST',price:100,price_date:'2026-09-09',period_end:'2026-07-26',revenue:10000,operating_income:2000,cash:1000,debt:500,shares:100,other_claims:0};
const data={symbol:'TEST',price_context:{context_id:'matching'}};
test('empty financials show unavailable, not fabricated value',()=>assert.equal(defaultCalculation(null,'TEST'),null));
test('other symbol financials never displayed',()=>assert.equal(defaultCalculation({input},'OTHER'),null));
test('example scenario never sets reviewed flags',()=>{const b=defaultCalculation({input:{...input,share_basis_checked:true,claims_checked:true}},'TEST');assert.equal(b.assumptions.reviewed,false);assert.equal(b.financials.share_basis_checked,false);assert.equal(b.financials.claims_checked,false);assert.equal(b.assumptions.scenarios[1].growth,.1);assert.equal(b.assumptions.scenarios[1].target_margin,.2);});
test('default calculation does not alter source object',()=>{const pack={input:{...input,share_basis_checked:true}};const before=JSON.stringify(pack);defaultCalculation(pack,'TEST');assert.equal(JSON.stringify(pack),before);});
test('incomplete required value stays missing',()=>assert.equal(defaultCalculation({input:{...input,debt:null}},'TEST'),null));
test('nonpositive margin not forcibly valued',()=>assert.equal(defaultCalculation({input:{...input,operating_income:-1}},'TEST'),null));
test('price context mismatch is not same cache',()=>assert.equal(matchedOutlook({context:{symbol:'TEST',price_context_id:'other'}},data),null));
test('ticker match alone insufficient',()=>assert.equal(matchedOutlook({context:{symbol:'TEST'}},data),null));
test('full matching context retained',()=>{const c={context:{symbol:'TEST',price_context_id:'matching'}};assert.equal(matchedOutlook(c,data),c);});
test('source ledger ticker mismatch not reused',()=>{const v=eventView({version:'source-schedule-0.6.2',symbol:'OTHER',candidates:[]},null,data,90);assert.equal(v.ledger,null);});
test('unconfirmed event date not promoted',()=>{const cache={context:{symbol:'TEST',price_context_id:'matching',research_date:'2026-09-10'},reports:{catalysts:{symbol:'TEST',scope:'catalysts',analysis_mode:'FORWARD_CATALYST_RISK',context:{research_date:'2026-09-10'},sources:[],items:[{title:'Uncertain',category:'OTHER',timing:'UNCONFIRMED',event_date:'2026-09-20',bucket:'UNKNOWN'}]}}};assert.equal(eventView(null,cache,data,90).visible.length,0);assert.equal(eventView(null,cache,data,'unknown').visible.length,1);});
test('old AI risk text without quote never becomes a main card',()=>assert.deepEqual(filingCards({symbol:'TEST',cards:[{evidence:[{quote:'',url:'https://www.sec.gov/Archives/edgar/data/123/doc.htm'}]}]},'TEST'),[]));
test('other symbol filing report ignored',()=>assert.deepEqual(filingCards({symbol:'OTHER',cards:[{evidence:[{quote:'real',url:'https://www.sec.gov/Archives/edgar/data/123/doc.htm'}]}]},'TEST'),[]));
test('source linked rule card retained without changing classification',()=>{const c={direction:'MIXED',evidence:[{quote:'We issued notes.',url:'https://www.sec.gov/Archives/edgar/data/123/doc.htm'}]};assert.equal(filingCards({symbol:'TEST',cards:[c]},'TEST')[0],c);});
test('unsafe source not linked by card picker',()=>assert.deepEqual(filingCards({symbol:'TEST',cards:[{evidence:[{quote:'hello',url:'javascript:alert(1)'}]}]},'TEST'),[]));
test('zero growth remains valid zero',()=>{const v=valuationDigest({symbol:'TEST',financials:input,base:{},reverse:{growth:0,years:5}},'TEST');assert.equal(v.growth,0);assert.equal(v.multiple,1);});
test('unsolved reverse not converted to zero',()=>{const v=valuationDigest({symbol:'TEST',financials:input,base:{},reverse:{growth:null,years:5}},'TEST');assert.equal(v.growth,null);assert.equal(v.multiple,null);});
test('stale verdict remains stale',()=>assert.equal(valuationDigest({symbol:'TEST',financials:input,base:{},reverse:{},verdict:'STALE_DATA'},'TEST').stale,true));
test('wrong valuation symbol rejected',()=>assert.equal(valuationDigest({symbol:'OTHER',financials:input,base:{}},'TEST'),null));
test('paid result cannot match other price context',()=>assert.equal(researchCacheIsCurrent({symbol:'TEST',scope:'catalysts',context:{price_context_id:'different'}},data),false));
test('paid result exact scope and context required',()=>{assert.equal(researchCacheIsCurrent({symbol:'TEST',scope:'catalysts',context:{price_context_id:'matching'}},data),true);assert.equal(researchCacheIsCurrent({symbol:'TEST',scope:'risks',context:{price_context_id:'matching'}},data),false);});
test('filing failure partial availability not success',()=>assert.match(humanFailure('period mismatch'),/연결하지 못/));
