import test from 'node:test';import assert from 'node:assert/strict';
import {inspectLocalBundle,readLocalBundle,localImportPayload,inputOriginLabel,MAX_LOCAL_BYTES} from './local-financials.mjs';
const base={schema:'signaldesk-sec-local-bundle-1',symbol:'EXM',submission:{cik:'1',name:'Example',tickers:['EXM']},companyfacts:{cik:1,facts:{}}};
const text=JSON.stringify(base);
test('local file internal identity check',()=>assert.equal(inspectLocalBundle(text,'EXM').name,'Example'));
test('file selection has no network operation',async()=>{const old=globalThis.fetch;globalThis.fetch=()=>{throw Error('NETWORK');};try{assert.equal((await readLocalBundle({size:text.length,text:async()=>text},'EXM')).symbol,'EXM');}finally{globalThis.fetch=old;}});
test('UTF BOM supported',()=>assert.equal(inspectLocalBundle('\uFEFF'+text,'EXM').cik,'1'));
test('wrong company no submit',()=>assert.throws(()=>inspectLocalBundle(text,'OTHER')));
test('different cik no submit',()=>assert.throws(()=>inspectLocalBundle(JSON.stringify({...base,companyfacts:{cik:2}}),'EXM')));
test('wrong submissions ticker',()=>assert.throws(()=>inspectLocalBundle(JSON.stringify({...base,submission:{cik:1,tickers:['OTHER']}}),'EXM')));
test('raw companyfacts or source-read diagnostic rejected',()=>{assert.throws(()=>inspectLocalBundle(JSON.stringify(base.companyfacts),'EXM'));assert.throws(()=>inspectLocalBundle('{"version":"source-reader"}','EXM'));});
test('missing file readable error',async()=>assert.rejects(()=>readLocalBundle(null,'EXM')));
test('oversize before file read',async()=>{let read=false;await assert.rejects(()=>readLocalBundle({size:MAX_LOCAL_BYTES+1,text:async()=>{read=true;return text;}},'EXM'));assert.equal(read,false);});
test('malformed data does not echo file contents',()=>assert.throws(()=>inspectLocalBundle('PRIVATE-FILE','EXM'),e=>!e.message.includes('PRIVATE-FILE')));
test('explicit import consent required',()=>assert.throws(()=>localImportPayload(text,'EXM',false,'SAVED')));
test('saved quote request does not embed invented price',()=>{const p=localImportPayload(text,'EXM',true,'SAVED');assert.equal(p.manual_quote,null);assert.equal(p.allow_local_import,true);});
test('manual price separated and exact',()=>assert.deepEqual(localImportPayload(text,'EXM',true,'MANUAL','223.67','2026-09-09').manual_quote,{close:223.67,date:'2026-09-09'}));
test('blank zero negative infinite manual prices rejected',()=>{for(const p of ['',0,-1,Infinity,true])assert.throws(()=>localImportPayload(text,'EXM',true,'MANUAL',p,'2026-09-09'));});
test('manual date missing rejected',()=>assert.throws(()=>localImportPayload(text,'EXM',true,'MANUAL',20,'')));
test('local file label is not live SEC verification',()=>{assert.equal(inputOriginLabel('SEC_LOCAL'),'사용자 제공 SEC 파일');assert.notEqual(inputOriginLabel('SEC_LOCAL'),inputOriginLabel('SEC'));});
