import test from 'node:test';
import assert from 'node:assert/strict';
import {filterCatalysts,scheduleText,countdownText,outlookMatches,missingScopes,publicationLabel} from './outlook.mjs';
const items=[{bucket:'D30'},{bucket:'D90'},{bucket:'D180'},{bucket:'UNKNOWN'}];
test('30/90/180 filters are cumulative, unknown dates never assigned',()=>{assert.equal(filterCatalysts(items,30).length,1);assert.equal(filterCatalysts(items,90).length,2);assert.equal(filterCatalysts(items,180).length,3);assert.deepEqual(filterCatalysts(items,'unknown'),[items[3]]);});
test('unsupported horizon displays no invented rows',()=>assert.deepEqual(filterCatalysts(items,999),[]));
test('empty arrays remain empty',()=>assert.deepEqual(filterCatalysts([],90),[]));
test('unknown timing does not expose a stale precise day',()=>assert.equal(scheduleText({timing:'UNCONFIRMED',event_date:'2026-11-17'}),'날짜를 아직 확인하지 못했습니다'));
test('estimated day is labeled estimated, with no official countdown',()=>{const c={timing:'ESTIMATED',event_date:'2026-11-17',days_to_start:69};assert.equal(scheduleText(c),'예상 · 2026-11-17');assert.equal(countdownText(c),null);});
test('exact schedule has countdown without probability',()=>assert.equal(countdownText({timing:'ANNOUNCED_DATE',event_date:'2026-11-17',days_to_start:69}),'D-69'));
test('today says time and completion need checking',()=>assert.equal(countdownText({timing:'ANNOUNCED_DATE',days_to_start:0}),'오늘 · 시각/진행 여부 확인'));
test('window overlap is not reported as exact date',()=>assert.equal(countdownText({timing:'ANNOUNCED_WINDOW',window_overlaps_today:true,days_to_start:-8}),'기간 진행 중 · 발생 여부 별도 확인'));
test('past and missing countdown not displayed',()=>{assert.equal(countdownText({timing:'ANNOUNCED_DATE',days_to_start:-1}),null);assert.equal(countdownText({timing:'UNCONFIRMED',days_to_start:5}),null);});
test('window retains both dates',()=>assert.equal(scheduleText({timing:'ANNOUNCED_WINDOW',window_start:'2026-10-01',window_end:'2026-10-31'}),'2026-10-01 ~ 2026-10-31'));
const c={symbol:'EXM',context_id:'abc'},r={symbol:'EXM',context_id:'abc',analysis_mode:'FORWARD_CATALYST_RISK',scope:'catalysts'};
test('result identity requires ticker + context + scope + mode',()=>{assert.equal(outlookMatches(r,c,'catalysts'),true);for(const bad of [{...r,symbol:'OTHER'},{...r,context_id:'old'},{...r,scope:'risks'},{...r,analysis_mode:'RETROSPECTIVE_WEB_RESEARCH'}])assert.equal(outlookMatches(bad,c,'catalysts'),false);});
test('partial completion requests only missing scope',()=>assert.deepEqual(missingScopes({catalysts:r},c),['risks']));
test('two missing purposes and no matching data',()=>assert.deepEqual(missingScopes({},c),['catalysts','risks']));
test('both results cached means no missing scopes',()=>assert.deepEqual(missingScopes({catalysts:r,risks:{...r,scope:'risks'}},c),[]));
test('old publication label differs from post-price publication',()=>{assert.match(publicationLabel.BEFORE_PRICE_DATE,/이전/);assert.match(publicationLabel.AFTER_PRICE_DATE,/이후/);});
