import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {eventInsight,splitNewsCards,selectBoardEvents,sourcesForEvent} from './signals.mjs';
import {eventView} from './desk.mjs';
const report={sources:[{id:'s1',url:'https://example.com/filing',title:'Synthetic fixture, not real company news'}]};
const entry=(title,category='OTHER')=>({id:'e1',title,category,candidates:[],ai:{title,source_ids:['s1'],date_source_ids:[],timing:'UNCONFIRMED',fact:'테스트용 저장 문장. 실제 기업 정보가 아닙니다.'},eventDate:null,windowStart:null,windowEnd:null});
const filing=()=>entry('FDA 접수(acceptance) 통지 및 검토타임라인(수락 시 PDUFA) — 시험용 sNDA','REGULATORY');

test('FDA filing is not described as approval',()=>{const x=eventInsight(filing(),report);assert.equal(x.kind,'FDA_FILING');assert.match(x.label,/접수 ≠ 승인/);assert.match(x.positive,/최종 승인과는 별개/);assert.match(x.negative,/접수 거절/);});
test('OS data in OTHER gets survival-specific criteria',()=>{const x=eventInsight(entry('SENTRY(Phase 3) 장기 전체생존(OS) 데이터'),report);assert.equal(x.kind,'CLINICAL_OS');assert.match(x.positive,/생존 개선/);assert.match(x.negative,/입증하지 못/);});
test('stage precedence prevents PDUFA word promoting acceptance to approval',()=>assert.equal(eventInsight(filing(),report).kind,'FDA_FILING'));
test('plain FDA decision has separate approval criteria',()=>assert.equal(eventInsight(entry('FDA PDUFA 허가 결정','REGULATORY'),report).kind,'FDA_DECISION'));
test('missing earnings announcement is not adverse news',()=>{const x=eventInsight(entry('다음 정기 분기실적 발표 — 회사 공지 미확인','EARNINGS'),report);assert.match(x.label,/호재·악재 아님/);assert.equal(x.tone,'neutral');assert.match(x.why,/일정 지연이 확인된 것은 아닙니다/);});
test('unknown event has no tautological made-up scenarios',()=>{const x=eventInsight(entry('기타 항목'),report);assert.equal(x.positive,null);assert.equal(x.negative,null);assert.match(x.label,/근거 부족/);});
test('specific cached AI scenarios can supply unknown event criteria',()=>{const e=entry('설비 점검');e.ai.positive_condition='핵심 설비의 재가동과 생산 정상화가 확인되면 공급 차질이 완화될 수 있습니다.';e.ai.negative_condition='점검 중 추가 결함과 가동 중단 연장이 확인되면 생산 차질이 커질 수 있습니다.';assert.match(eventInsight(e,report).basis,/저장 AI/);});
test('unsafe links cannot substantiate AI-only scenario',()=>{const e=entry('설비 점검');e.ai.positive_condition='핵심 설비의 재가동과 생산 정상화가 확인되면 공급 차질이 완화될 수 있습니다.';e.ai.negative_condition='점검 중 추가 결함과 가동 중단 연장이 확인되면 생산 차질이 커질 수 있습니다.';const x=eventInsight(e,{sources:[{id:'s1',url:'javascript:alert(1)'}]});assert.equal(x.positive,null);assert.match(x.label,/원문 미연결/);});
test('percentage price forecast rejected as condition',()=>{const e=entry('특별 행사');e.ai.positive_condition='행사에서 주가가 50% 상승할 것이며 확실한 호재라고 판단합니다.';e.ai.negative_condition='다음 행사에서 추가 설비 투자 부담이 생기면 사업 현금흐름이 악화됩니다.';assert.equal(eventInsight(e,report).positive,null);});
test('conditional positive cannot appear in both news columns',()=>{const x=splitNewsCards([{id:'x',direction:'POSITIVE',state:'CONDITIONAL'}]);assert.equal(x.positive.length,0);assert.equal(x.negative.length,0);assert.equal(x.other.length,1);});
test('realized positive stays positive only',()=>{const x=splitNewsCards([{id:'x',direction:'POSITIVE',state:'REPORTED_FACT'}]);assert.equal(x.positive.length,1);assert.equal(x.negative.length,0);});
test('mixed disclosed risk stays one card not two',()=>{const x=splitNewsCards([{id:'x',direction:'MIXED',state:'EXPOSURE'}]);assert.equal(x.positive.length,0);assert.equal(x.negative.length,1);});
test('duplicate news ID counted once',()=>{const c={id:'x',direction:'NEGATIVE',state:'EXPOSURE'};assert.equal(splitNewsCards([c,c]).negative.length,1);});
test('empty cards do not invent news',()=>assert.deepEqual(splitNewsCards(null),{positive:[],negative:[],other:[]}));
test('conferences not positive merely because attended',()=>{const x=eventInsight(entry('Investor conference','CONFERENCE'),report);assert.equal(x.tone,'neutral');assert.match(x.label,/참석 자체는 호재 아님/);});
test('product milestones remain non-biotech-specific',()=>{const x=eventInsight(entry('Cloud product release','PRODUCT'),report);assert.equal(x.kind,'PRODUCT');assert.match(x.positive,/주문/);assert.doesNotMatch(x.positive,/FDA|임상/);});
test('funding is not assumed to be dilutive before terms exist',()=>{const x=eventInsight(entry('Financing','FINANCING'),report);assert.match(x.label,/조건 확인/);assert.match(x.negative,/할인 발행/);});
test('debt milestone has specific refinance criteria',()=>assert.match(eventInsight(entry('Debt maturity','DEBT'),report).negative,/차환 실패/));
test('conflicted date does not gain directional certainty',()=>{const e={...filing(),conflict:true};const x=eventInsight(e,report);assert.match(x.label,/판단 보류/);assert.equal(x.fact,'');});
test('raw AI fact not upgraded to verified fact',()=>{const x=eventInsight(filing(),report);assert.match(x.basis,/새 기업 분석 아님/);assert.equal(x.fact,filing().ai.fact);});
test('source picker deduplicates URL links',()=>{const e=filing();e.candidates=[{source_url:'https://example.com/filing'}];assert.equal(sourcesForEvent(e,report).length,1);});
test('unknown source IDs not replaced with arbitrary report source',()=>{const e=filing();e.ai.source_ids=['not-found'];assert.equal(sourcesForEvent(e,report).length,0);});
const dated=(day,id)=>({...entry('event '+id),id,eventDate:day});
const view={researchDate:'2026-09-12',entries:[dated('2026-09-01','past'),dated('2026-09-20','soon'),dated('2026-12-01','later'),{...filing(),id:'unknown'}]};
test('all default includes future and unknown, never past',()=>assert.deepEqual(selectBoardEvents(view).map(x=>x.id),['soon','later','unknown']));
test('30 day filter excludes undated items',()=>assert.deepEqual(selectBoardEvents(view,30).map(x=>x.id),['soon']));
test('unknown filter contains only unknown dates',()=>assert.deepEqual(selectBoardEvents(view,'unknown').map(x=>x.id),['unknown']));
test('aging report date cannot keep past event upcoming',()=>assert.deepEqual(selectBoardEvents(view,'all','2027-01-01').map(x=>x.id),['unknown']));
test('invalid today does not manufacture ordering',()=>assert.deepEqual(selectBoardEvents(view,'all','bad'),[]));
test('same record exact duplicate collapses',()=>assert.equal(selectBoardEvents({...view,entries:[filing(),filing()]}).length,1));
test('different source/date records not collapsed by category',()=>assert.equal(selectBoardEvents({...view,entries:[dated('2026-09-20','a'),dated('2026-09-22','b')]}).length,2));
test('price-context mismatch still rejects another company cache',()=>{const d={symbol:'KPTI',price_context:{context_id:'a'}};const c={context:{symbol:'NVDA',price_context_id:'b',research_date:'2026-09-12'},reports:{catalysts:{symbol:'NVDA',scope:'catalysts',items:[filing()]}}};assert.equal(eventView(null,c,d).entries.length,0);});
test('interpretation does not mutate report or entry',()=>{const e=filing(),snapshot=JSON.stringify([e,report]);eventInsight(e,report);assert.equal(JSON.stringify([e,report]),snapshot);});
test('display rules never call network',()=>{const original=globalThis.fetch;globalThis.fetch=()=>{throw new Error('unexpected fetch');};try{eventInsight(filing(),report);selectBoardEvents(view);splitNewsCards([]);}finally{globalThis.fetch=original;}});
test('main UI has no valuation section or requests',()=>{const main=fs.readFileSync(new URL('../app/page.jsx',import.meta.url),'utf8'),desk=fs.readFileSync(new URL('../components/DeskOverview.jsx',import.meta.url),'utf8');for(const value of [main,desk])assert.doesNotMatch(value,/desk-price|api\/v1\/decision\/(state|calculate)|가정·자료 설정|가치평가 자료/);});
test('old advanced URL cannot resurrect valuation',()=>assert.match(fs.readFileSync(new URL('../app/advanced/page.jsx',import.meta.url),'utf8'),/export \{default\} from '\.\.\/page'/));
test('release label is shared, not stale hardcoded footer',()=>{const s=fs.readFileSync(new URL('../app/page.jsx',import.meta.url),'utf8');assert.match(s,/RELEASE_VERSION/);assert.doesNotMatch(s,/Portfolio v1\.0\.2|간단 화면 · 1\.0\.[0-5]/);});
test('empty news explanation is coverage, not absence',()=>{const s=fs.readFileSync(new URL('../components/NewsEventBoard.jsx',import.meta.url),'utf8');assert.match(s,/전체 뉴스를 검색해/);assert.match(s,/결과가 아닙니다/);});

test('operating system launch is not clinical OS',()=>assert.equal(eventInsight(entry('Windows OS 제품 출시','PRODUCT'),report).kind,'PRODUCT'));
