import test from 'node:test';
import assert from 'node:assert/strict';
import {matchingWatchState,driversBySide,scanHeadline,canAutoScan} from './stock-watch.mjs';
const base={enabled:true,visible:true,working:'',externalBusy:false,serverBusy:false,contactConfigured:true};
test('watch state rejects different symbol',()=>assert.equal(matchingWatchState({symbol:'OTHER'},'TEST'),null));
test('nested company mismatch cannot leak',()=>{const x=matchingWatchState({symbol:'TEST',drivers:{symbol:'OTHER'},dilution:{symbol:'OTHER'}},'TEST');assert.equal(x.drivers,null);assert.equal(x.dilution,null);});
test('no report is not no dilution',()=>assert.equal(scanHeadline(null).tone,'unknown'));
test('partial data is never all clear',()=>assert.equal(scanHeadline({status:'PARTIAL',alerts:[]}).tone,'watch'));
test('old scan is prominently stale',()=>assert.match(scanHeadline({status:'SCANNED',stale:true,alerts:[]}).title,/저장/));
test('empty scan states scanned scope only',()=>assert.match(scanHeadline({status:'SCANNED',alerts:[]}).title,/검토한 범위/));
test('sources required for a driver',()=>assert.deepEqual(driversBySide({symbol:'TEST',drivers:[{side:'UPSIDE',sources:[]}]},'TEST','UPSIDE'),[]));
test('sides remain separate',()=>{const x={symbol:'TEST',drivers:[{side:'UPSIDE',sources:[{}]},{side:'DOWNSIDE',sources:[{}]}]};assert.equal(driversBySide(x,'TEST','UPSIDE').length,1);});
test('unknown side not silently bullish',()=>assert.deepEqual(driversBySide({symbol:'TEST',drivers:[{side:'UPSIDE',sources:[{}]}]},'TEST','UNKNOWN'),[]));
test('automatic requests default to off',()=>assert.equal(canAutoScan({...base,enabled:false}),false));
test('automatic scan stops while hidden',()=>assert.equal(canAutoScan({...base,visible:false}),false));
test('automatic scan stops while another feature busy',()=>assert.equal(canAutoScan({...base,externalBusy:true}),false));
test('automatic scan stops during server work',()=>assert.equal(canAutoScan({...base,serverBusy:true}),false));
test('automatic scan stops during own request',()=>assert.equal(canAutoScan({...base,working:'sec'}),false));
test('automatic scan needs contact config',()=>assert.equal(canAutoScan({...base,contactConfigured:false}),false));
test('explicit enabled visible idle consented scan allowed',()=>assert.equal(canAutoScan(base),true));
test('source objects not mutated by picker',()=>{const x={symbol:'TEST',drivers:[{side:'UPSIDE',sources:[{}]}]},before=JSON.stringify(x);driversBySide(x,'TEST','UPSIDE');assert.equal(JSON.stringify(x),before);});
