import test from 'node:test';
import assert from 'node:assert/strict';
import {thesisItems,hasThesisBlock,draftForSymbol,canResumeDraft,matchingWatchState} from './stock-watch.mjs';
const doc={symbol:'TEST',version:'thesis-engine-1.2.0',identity_confirmed:true,bottlenecks:[{title:'linked',sources:[{url:'https://example.com'}],milestone_status:'CONDITIONAL'}]};
test('thesis wrong issuer is never shown',()=>assert.deepEqual(thesisItems(doc,'OTHER'),[]));
test('old driver result is not a new thesis',()=>assert.deepEqual(thesisItems({...doc,version:'stock-drivers-1.1.0'},'TEST'),[]));
test('unidentified issuer cannot show thesis cards',()=>assert.deepEqual(thesisItems({...doc,identity_confirmed:false},'TEST'),[]));
test('completed milestone is not recycled as pending',()=>assert.deepEqual(thesisItems({...doc,bottlenecks:[{...doc.bottlenecks[0],milestone_status:'COMPLETED'}]},'TEST'),[]));
test('linked thesis retains actual text',()=>assert.equal(thesisItems(doc,'TEST')[0].title,'linked'));
test('null or uncited summary is not filled with a template',()=>{assert.equal(hasThesisBlock(null),false);assert.equal(hasThesisBlock({text:'hello',sources:[]}),false);});
test('valid summary rendered',()=>assert.equal(hasThesisBlock({text:'supported',sources:[{}]}),true));
test('wrong company draft rejected',()=>assert.equal(draftForSymbol({symbol:'OTHER',version:doc.version},'TEST'),null));
test('nested wrong company draft rejected',()=>assert.equal(matchingWatchState({symbol:'TEST',research_draft:{symbol:'OTHER',version:doc.version}},'TEST').research_draft,null));
test('resume requires same date and live draft',()=>{const d={symbol:'TEST',version:doc.version,can_resume:true,stale:false,research_date:'2026-09-12'};assert.equal(canResumeDraft(d,'TEST','2026-09-12'),true);assert.equal(canResumeDraft({...d,stale:true},'TEST','2026-09-12'),false);assert.equal(canResumeDraft(d,'TEST','2026-09-13'),false);});
